# -*- coding: utf-8 -*-
"""Python Assignment 2 Part1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RvlGmMep939zuCKiUqlymINYp6FwKFyA
"""

pip install requests beautifulsoup4 requests-html

import pandas as pd
from urllib.parse import urlparse
import numpy as np
import nltk.data
from requests_html import HTMLSession
import requests
from bs4 import BeautifulSoup

url = requests.get('https://www.cbc.ca/news/canada')
soup = BeautifulSoup(url.content, 'html.parser')

news_titles = soup.select('h3.headline')

news_titles[0].text

"""Scrapping the news title"""

for news_title in news_titles:
    print(news_title.text)

news_titles_df = pd.DataFrame(news_titles)

news_titles_df

"""Scrapping the links

"""

all_links = [i['href'] for i in soup.find_all('a', href=True)]
print(all_links)

for i in soup.find_all('a', href=True):
  print(i['href'])

"""Only getting the link with /news/canada"""

for i in soup.find_all('a', href=True):
    if 'news/canada' in i['href']:
        print('https://www.cbc.ca/'+i['href'])

"""Only getting news in toronto with reading the html"""

for i in soup.find_all('a', href=True):
    if 'news/canada/toronto' in i['href']:
        print('https://www.cbc.ca/'+i['href'])

"""Getting the news among different cities"""

for i in soup.find_all('a', href=True):
    if 'news/canada/toronto' in i['href']:
        print('Toronto'+':'+'https://www.cbc.ca/'+i['href'])
    if 'news/canada/calgary' in i['href']:
        print('Calgary'+':'+'https://www.cbc.ca/'+i['href'])
    if 'news/canada/hamilton' in i['href']:
        print('Hamilton'+':'+'https://www.cbc.ca/'+i['href'])
    if 'news/canada/montreal' in i['href']:
        print('Montreal'+':'+'https://www.cbc.ca/'+i['href'])

